module.exports = {
  Register: require('./register'),
  Login: require('./login'),
  RefreshToken: require('./refreshtoken'),
  GetProfile: require('./getprofile'),
  UpdateProfile: require('./updateprofile'),
  VerifyEmail: require('./verifyemail'),
  ChangePassword: require('./changepassword'),
  DeleteAccount: require('./deleteaccount'),
  ForgotPassword: require('./forgotpassword'),
  Logout: require('./logout'),
  ResetPassword: require('./resetPassword'),
  RevokeRefreshToken: require('./revokerefreshtoken'),
  SendVerificationEmail: require('./sendverificationemail'),
  GetAllUsers: require('./getallusers'),
  UpdateRole: require('./updaterole'),
  GetRoleChangeHistory: require('./getrolechangehistory'),
  GetRoleChangeHistoryCSV: require('./getrolechangehistorycsv'),
  UpdateProfileImage: require('./updateprofileimage')
};
