# Nombre del workflow, aparecerá en la pestaña "Actions" de GitHub
name: Generate Sitemap Daily Realidad Nacional

# Define cuándo se debe ejecutar esta acción
on:
  schedule:
    # Se ejecuta todos los días a las 3:00 AM UTC. 
    # (En Uruguay, esto sería a las 12:00 AM o medianoche).
    - cron: '0 3 * * *'
  
  # También permite ejecutarlo manualmente desde la pestaña "Actions" en GitHub
  workflow_dispatch:

jobs:
  trigger_sitemap_generation:
    # Usamos la última versión de Ubuntu para ejecutar la tarea
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Sitemap Regeneration
        run: |
          curl -X POST \
            -H "X-Regeneration-Secret: ${{ secrets.SITEMAP_SECRET }}" \
            "${{ secrets.SITEMAP_ENDPOINT_URL }}"